### ISSUE TITLE
Hulp [DO3]: Domein

### ISSUE THREAD

**Issue by arothuis-hu** [opasta/cisq1-lingo-opasta#3]
Je Game object kan een lijst van Rounds bijhouden. 
Elke round heeft een wordToGuess in zich.

Via Game kan je dan een `guess` uitvoeren, die weer wordt aangeroepen op de huidige (= de laatste) ronde.
De Game kan ook vertellen hoe lang het volgende woord moet zijn, gebaseerd op de huidige ronde.

Je hoeft dan dus niet meer de oldLength mee tegen, zoals hier:
https://github.com/opasta/cisq1-lingo-opasta/blob/47848913de3aafc781020d5a6484628c28edd54c/src/main/java/nl/hu/cisq1/lingo/trainer/domain/Game.java#L31-L37

Het Game object bevat alle kennis die nodig is om het spel te spelen. Dit is onderdeel van de `Game` abstraction.
De gebruiker van Game hoeft niet te weten hoe rondes werken. Encapsulation van Game zorgt daarvoor.

**Comment by opasta** [comment]
public Integer getNextWordLength() {
        int newLength = this.getLastRound().getWordLength() + 1;

        if (newLength == 8 || newLength < 5) {
            newLength = 5;
        }

        return newLength;
    }
